spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.88.129:3306/glmall_ums?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: glmall-member


mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
    port: 8000